apiVersion: v1
kind: Service
metadata:
  name: crypto-payments
  labels:
    app: crypto-payments
spec:
  selector:
    app: crypto-payments
  ports:
    - name: http
      port: 3003
      targetPort: http
      protocol: TCP
